# THIS DOCKER FILE IS FOR OPENSHIFT DEPLOYMENT
# DATASOURCE IS BEING CONFIGURED USING ENVIRONMENT VARIABLES IN OPENSHIFT INSTANCE
# https://access.redhat.com/containers/?tab=tech-details#/registry.access.redhat.com/jboss-eap-7/eap70-openshift
FROM registry.access.redhat.com/jboss-eap-7/eap70-openshift:1.4-36

MAINTAINER "Alex Eng" <aeng@redhat.com>

EXPOSE 8080

USER root
RUN cd /etc/pki/ca-trust/source/anchors/ && curl http://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem -O && update-ca-trust


USER jboss

# copy war file
# assuming war file is in the same directory
ADD ROOT.war $JBOSS_HOME/standalone/deployments/ROOT.war
