export const GET_INFO_REQUEST = 'GET_INFO_REQUEST'
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS'
export const GET_INFO_FAILED = 'GET_INFO_FAILED'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const TRANSLATE_FILE_REQUEST = 'TRANSLATE_FILE_REQUEST'
export const TRANSLATE_FILE_SUCCESS = 'TRANSLATE_FILE_SUCCESS'
export const TRANSLATE_FILE_FAILED = 'TRANSLATE_FILE_FAILED'

export const GET_SUPPORTED_LOCALES_REQUEST = 'GET_SUPPORTED_LOCALES_REQUEST'
export const GET_SUPPORTED_LOCALES_SUCCESS = 'GET_SUPPORTED_LOCALES_SUCCESS'
export const GET_SUPPORTED_LOCALES_FAILED = 'GET_SUPPORTED_LOCALES_FAILED'

export const LOGOUT = 'LOGOUT'

export const TOGGLE_LOGIN_FORM_DISPLAY = 'TOGGLE_LOGIN_FORM_DISPLAY'

export const enum MSG_TYPE {
    ERROR,
    WARNING,
    INFO
}
