# THIS DOCKER FILE IS FOR OPENSHIFT DEPLOYMENT
# DATASOURCE IS BEING CONFIGURED USING ENVIRONMENT VARIABLES IN OPENSHIFT INSTANCE
#
# Required file in same directory:
# - ROOT.war - packaged war file
#
# https://access.redhat.com/containers/?tab=tech-details#/registry.access.redhat.com/jboss-eap-7/eap70-openshift
FROM registry.access.redhat.com/jboss-eap-7/eap70-openshift:latest

MAINTAINER "Alex Eng" <aeng@redhat.com>

EXPOSE 8080

USER root

# copy all certs from certs/ directory
COPY certs/ /etc/pki/ca-trust/source/anchors/

RUN update-ca-trust extract


USER jboss

# copy war file
# assuming war file is in the same directory
COPY ROOT.war $JBOSS_HOME/standalone/deployments/ROOT.war
